quarkus.http.port=9090


# Para producción, usar rutas absolutas
%prod.smallrye.jwt.sign.key.location=/app/keys/private.pem
%prod.smallrye.jwt.encrypt.key.location=/app/keys/public.pem
%prod.mp.jwt.verify.publickey.location=/app/keys/public.pem
%prod.mp.jwt.verify.issuer=token-api