quarkus.http.port=9090


# Para producción, usar rutas absolutas
%prod.smallrye.jwt.sign.key.location=keys/private.pem
%prod.smallrye.jwt.encrypt.key.location=keys/public.pem
%prod.mp.jwt.verify.publickey.location=keys/public.pem
%prod.mp.jwt.verify.issuer=token-api